### ISSUE TITLE
maskTextFieldTelephone duplicate characters when typing

### ISSUE THREAD

**Issue by mixdesign** [viniciusmo/VMaskTextField#4]
When I changed the format (to `self.maskTextFieldTelephone.mask = @"+7 (###) ### ## ##";` ) in demo project, I get this strange result:

![vmasktf](https://cloud.githubusercontent.com/assets/198882/6101187/c20bcc1c-b049-11e4-835d-71fdb645ec39.gif)

**Comment by viniciusmo** [comment]
Please, test :)
