### ISSUE TITLE
Erro na MASK

### ISSUE THREAD

**Issue by thiagoleaowd** [viniciusmo/VMaskTextField#5]
Vinicius, eu adicionei a MASK em apenas um textfield, que foi a data, porém na mesma view tem outros textfields que mantive o padrão.

Porém acho que a função sobrescreve a do textfields, e nenhum outro textfield sem mascaram funcionam.

@IBOutlet weak var data: VMaskTextField!

override func viewDidLoad() {
     super.viewDidLoad()
     data.mask = "##/##/####"
     data.delegate       = self
        
     descricao.delegate  = self
     price.delegate      = self
     size.delegate       = self
    }

func textField(textField: VMaskTextField, shouldChangeCharactersInRange range: NSRange, replacementString string: String) -> Bool {
        return data.shouldChangeCharactersInRange(range, replacementString: string);
    }

Pode me ajudar?
Obrigado

**Comment by viniciusmo** [comment]
Olá Thiago,tudo bom?
Basta verificar se textField é igual a data no delegate.Por exemplo,
if (textField == data){ 
   //chama data.shouldChangeCharactersInRange
}

**Comment by viniciusmo** [comment]
Deu certo Thiago?

**Comment by thiagoleaowd** [comment]
Deu certo sim, Vinicius!
Te agradeço pela resposta rápida.
Excelente módulo.

func textField(textField: UITextField, shouldChangeCharactersInRange range: NSRange, replacementString string: String) -> Bool {
        if (textField == data){
            return data.shouldChangeCharactersInRange(range, replacementString: string);
        }
        return true
    }

Abraços

**Comment by viniciusmo** [comment]
Valeu!
