### ISSUE TITLE
Unknown class VMaskTextField in interface builder file (using Pods installation)

### ISSUE THREAD

**Issue by sidan** [viniciusmo/VMaskTextField#6]
I followed the installation guide, everything is fine, outlets setup, but when viewDidLoad gets called, it breaks with the following message:

"Unknown class VMaskTextField in interface builder file" -> I have defined the class for the textfield using Identity Inspector

I've deleted from the Pods and just paste the VMaskTextField class into my project. All config the same, then it works. So, I think it can be something related to the Pods.

Best Regards,

Sidan

**Comment by viniciusmo** [comment]
Thanks man! I will verify this.
